# Site settings
title:       Chris Rinaldi | Software Engineer + Data Scientist
email:       cgrinaldi@gmail.com
author:      Chris Rinaldi
description: "Chris Rinaldi is a data scientist who has decided to enroll in a programming bootcamp. Please join him as he documents his experience at Hack Reactor."
baseurl:     ""
url:         "http://cgrinaldi.github.io"

# Google analytics
google_analytics: "UA-56717704-1"

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: cgrinaldi
twitter_username: cgrinaldi
google_plus_id: 117051063148631308459
linkedin_username: christopher-rinaldi/37/4b1/885
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
